Walkover-Web-Solution/Giddh-Website

Inventory-Management-software.php
giddh-main-features.php
invoice-software.php
restaurant-software.php
retail-software.php
startup-software.php
tourism-software.php

Hi
We have created some new pages, please upload the requested files

New Pages Updation Required

---

features.php
footScript.php
head.php
header.html
index.php

mustafa | superform load issue

---

head.php

Arpit | Update head.php | Redirect form www to non-www

---

package-lock.json
package.json
src/components/header.js
src/data/metadata.json
src/pages/_app.js

S1T019 :: meta tags added in head comp

---

src/data/metadata.json

UAE section adedd in metadata.json file

S1T019 UAE section Adedd

---

src/data/metadata.json

S1T019 : metadata file completed

---

src/components/header.js
src/pages/v2/login.js

https://app.clickup.com/t/85zu0fyk7

Ravinder | Created new login page

---

src/pages/all-features.js

Divyanshu | When user is clicking on the search tab then search page is not getting open

---

src/pages/pricing.js
src/scss/scsscomps/_pricing.scss

https://app.clickup.com/t/86790d7hg

Divyanshu | Giddh website plan and pricing page changes

---

src/pages/pricing.js
src/scss/scsscomps/_pricing.scss

Pricing Page - https://app.clickup.com/t/86790d7hg

Dev to Main

---

src/pages/pricing.js
src/scss/scsscomps/_pricing.scss

https://app.clickup.com/t/86790d7hg

Divyanshu | Bank integration content change for other country

---

src/pages/all-features.js

https://app.clickup.com/t/86cu0ddcp

Divyanshu | Main | Changes in the GIDDH website

---

src/pages/all-features.js

https://app.clickup.com/t/86cu3buz1

Divyanshu | Main | Show Videos in the GIDDH panel in the software and in the website

---

_posts/blog/free-business-accounting-software-for-uk-vat-filling.mdx
_posts/blog/giddh-books-revolutionizing-modern-accounting.mdx
src/pages/contacts.js
src/pages/login.js
src/pages/privacy-policy.js
src/pages/security.js
src/pages/terms.js
src/scss/scsscomps/_security.scss

https://app.clickup.com/t/86cxgrrz7

Shivani | Main | On website H1 and H2 tags are missing on multiple pages

---

public/js/helper.js
src/components/bannerSection.js

Reverts Walkover-Web-Solution/Giddh-Website#409

Revert "Dilpreet | Main | Prod - Contact sales button is not working on website on mobile resolution"

---

src/components/blogs/postList.js
src/data/data.json
src/pages/in/e-invoice.js
src/pages/in/tallyplusgiddh.js
src/pages/inventory-management-software.js
src/scss/scsscomps/_giddh-plus-tally.scss

https://app.clickup.com/t/86cxndrdx

Shivani | Main | Website - Onpage Suggestions Report

---

src/data/metadata.json

https://app.clickup.com/t/86cxnu5v1

Shivani | Main | Non-Targeted Meta Title and Description Update

---

public/_redirects
src/components/header.js
src/data/metadata.json

https://app.clickup.com/t/86cxq63h7

Shivani | Main | Giddh website - India (all issues) - 15th Jan, 2025

---

src/data/metadata.json

Add deleted code 
https://app.clickup.com/t/86cxnu5v1

Divyanshu | Main | Non-Targeted Meta Title and Description Update

---

src/pages/blog/[slug].js
src/scss/scsscomps/_blog.scss

Divyanshu | Web | Design Fixes 

---

src/data/pricingData.json

https://app.clickup.com/t/86d025kyd

PIYUSH | WEB | Updated GST VAT & other pricing features

---

src/components/NewComps/Banner/index.js
src/components/NewComps/Features/Features.module.scss
src/components/NewComps/Features/index.js

Refactored the online-accounting-software page for cleaner structure and improved readability.

refactored(giddh): online-accounting-software page
